#' calculate_metrics
#'
#' calculate_metrics calculates for each edgelist in a list of edgelists the folowing
#' network-level metrics: number of nodes, leading eigenvector modularity, weighted
#' distance, weighted diameter, generalized clustering coefficient, and eigenvector
#' centralization
#'
#' @param emp_el a list of matrices generated by the function import_emp(), with each matrix representing an augmented edgelist where the first two columns indicate the sending and receiving node of a tie, respectively, the third column indicates the tie weight, the first element of the fourth column indicates the number of nodes in the network, and the first element of the fifth column indicates the number of ties in the network.
#'
#' @return a dataframe of network metrics, where each row represents an edgelist fed into the function, and the first column represents the index of those edgelists. Columns 2-7 represent (in this order): number of nodes, leading eigenvector modularity, weighted distance, weighted diameter, generalized clustering coefficient, and eigenvector centralization of each network.
#' @export
#'
#' @examples
#' emp_el_w <- readRDS("./data/Effective_el_emp_w")
#' weighted_metrics <- calculate_metrics(emp_el_w)
calculate_metrics <- function(emp_el) {

  require(tnet); require(igraph); require(sna)

  metrics <- data.frame(index = NA, n = NA, mod = NA, dist = NA, diam = NA, clust = NA, cent = NA)
  metrics <- metrics[FALSE,]

  for (y in 1:length(emp_el)) {

    a <- emp_el[[y]]
    i <- a[,1]; j <- a[,2]; w <- a[,3]; b <- cbind(i, j, w)

    ig <- graph.data.frame(b, directed = FALSE)
    dens <- graph.density(ig) / 2
    cent <- igraph::evcent(ig, weights = w, scale = FALSE)
    Ce.ei <- (-sum(cent$vector - max(cent$vector))) / sum(rep(1, cent$options$n) - cent$vector)
    Newman.mod <- leading.eigenvector.community(ig, weights = w)$modularity
    diam <- diameter(ig, directed = FALSE, weights = w)
    size <- cent$options$n

    c <- symmetrise_w(b)
    Cl.wgm <- clustering_w(c, measure = "gm")
    dist.mat <- distance_w(c)
    dist.w <- mean(dist.mat, na.rm = TRUE)

    tmp <- data.frame(index = y, n = size, mod = Newman.mod, dist = dist.w, diam = diam, clust = Cl.wgm, cent = Ce.ei)

    metrics <- rbind(metrics, tmp)
  }

  return(metrics)
}
